/* ユーザー情報取得API */
export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

/* ユーザー情報削除 */
export const DELETE_USERS_START = 'DELETE_USERS_START';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAIL = 'DELETE_USERS_FAIL';
